baseURL = "https://silveiralexf.github.io/"
languageCode = "en-us"
theme = "almeida-cv"
title = "silveiralexf"
publishDir = "docs"

[params]
colorDark = "#666"
colorLight = "#fff"
colorPageBackground = "#ddd"
colorPrimary = "#121212"
colorPrimaryText = "#fff"
colorRightColumnBackground = "#f5f5f5"
colorSecondary = "#aaa"
pages = 1
